"""
Draw structures generated by picofold.

Makes two files:
  picofold_structure.png   the true structure of one test window, next to
                           four structures the model generated for its
                           sequence (each with the true one in gray behind it)
  picofold_folding.gif     one generation from start to finish: a cloud of
                           random points condensing into a structure

Needs the trained model (picofold.pt, written by picofold.py),
test_data.txt, matplotlib and pillow.

Usage:
  python picofold_visualizer.py          # test window 5, a helix
  python picofold_visualizer.py 123      # or choose test window 123

Written by Claude
"""

import sys
import math
import numpy as np
import torch
import matplotlib
matplotlib.use('Agg')                     # draw to files, no window
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

# Reuse picofold.py as a module: importing it builds the model but trains nothing,
# because its training and evaluation sit behind a __main__ guard.
from picofold import AMINO_ACIDS, L, SAMPLE_STEPS, SCALE, TAU, device, model, load, lddt, drmsd

model.load_state_dict(torch.load('picofold.pt', map_location=device))
test_seq, test_xyz = load('test_data.txt')

# -----------------------------------------------------------------------------
# Pick a test window

idx = int(sys.argv[1]) if len(sys.argv) > 1 else 5      # window 5 is a helix
seq = test_seq[idx:idx + 1].to(device)                 # (1, L)
true = test_xyz[idx].numpy()                           # (L, 3) Angstroms
seq_str = ''.join(AMINO_ACIDS[a] for a in test_seq[idx].tolist())
print(f"test window {idx}: {seq_str}")

# -----------------------------------------------------------------------------
# Generate, keeping every intermediate step
#
# Same Euler-Maruyama sampler as generate() in picofold.py, except it returns the
# whole trajectory, not just the final structure. Kept separate so picofold.py
# stays simple; if you change the sampler there, change it here too.

@torch.no_grad()
def generate_trajectory(seq):
    x = torch.randn(seq.shape[0], L, 3, device=seq.device)
    dt = 1.0 / SAMPLE_STEPS
    frames = [x * SCALE]
    for i in range(SAMPLE_STEPS):
        t = i * dt
        x = x - x.mean(dim=1, keepdim=True)
        v = model(seq, x, torch.full((seq.shape[0],), t, device=seq.device))
        if t < 0.99:
            score = -(x - t * v) / (1 - t)
            w = (1 - t) / (t + 0.01)
            # Euler-Maruyama: x = x + drift * dt + diffusion * math.sqrt(dt) * torch.randn_like(x)
            x = x + (v + w * score) * dt + math.sqrt(2 * dt * w * TAU) * torch.randn_like(x)
        else:
            x = x + v * dt
        frames.append(x * SCALE)
    return torch.stack(frames, dim=1)                  # (B, steps+1, L, 3)

torch.manual_seed(0)
trajectories = generate_trajectory(seq.repeat(4, 1))  # four samples of the same sequence
samples = trajectories[:, -1]                          # (4, L, 3) final structures
scores = [lddt(s, true.tolist()) for s in samples.tolist()]
errors = [drmsd(s, true.tolist()) for s in samples.tolist()]

# -----------------------------------------------------------------------------
# Drawing helpers

COLORS = plt.cm.rainbow(np.linspace(0, 1, L))   # blue at the start of the chain, red at the end

def orientation(xyz):
    # A rotation that lays the structure's longest dimension left to right
    # (its principal axes), which shows a helix side-on, coils visible.
    _, _, Vt = np.linalg.svd(xyz - xyz.mean(0))
    R = Vt.T
    if np.linalg.det(R) < 0:
        R[:, 2] *= -1                            # a rotation, not a mirror
    return R

def superpose(mobile, target):
    # Rotate and shift `mobile` (L, 3) onto `target` (L, 3) so the two are
    # easy to compare by eye (the Kabsch algorithm). Only used for drawing.
    a, b = mobile - mobile.mean(0), target - target.mean(0)
    U, _, Vt = np.linalg.svd(a.T @ b)
    d = np.sign(np.linalg.det(U @ Vt))           # avoid returning a mirror image
    return a @ (U @ np.diag([1, 1, d]) @ Vt) + target.mean(0)

def smooth(xyz, n=8):
    # A smooth curve through the C-alpha atoms (a Catmull-Rom spline), n points
    # per residue-to-residue segment. Straight segments make a helix look
    # jagged, since the chain turns about 100 degrees at every residue;
    # molecular viewers draw the backbone this way too.
    p = np.vstack([xyz[0], xyz, xyz[-1]])            # repeat the ends
    curve = []
    for i in range(1, len(p) - 2):
        p0, p1, p2, p3 = p[i - 1], p[i], p[i + 1], p[i + 2]
        for s in np.linspace(0, 1, n, endpoint=False):
            curve.append(0.5 * (2 * p1 + (p2 - p0) * s + (2 * p0 - 5 * p1 + 4 * p2 - p3) * s**2
                                + (3 * p1 - p0 - 3 * p2 + p3) * s**3))
    curve.append(xyz[-1])
    return np.array(curve)

def draw_chain(ax, xyz, colored=True, lw=5, size=30, alpha=1.0):
    # A smooth tube along the chain, colored blue to red, with a small ball
    # at each C-alpha atom.
    curve = smooth(xyz)
    colors = plt.cm.rainbow(np.linspace(0, 1, len(curve)))
    for i in range(len(curve) - 1):
        color = colors[i] if colored else (0.6, 0.6, 0.6)
        ax.plot(*curve[i:i + 2].T, color=color, lw=lw, alpha=alpha, solid_capstyle='round')
    ax.scatter(*xyz.T, c=COLORS if colored else [(0.6, 0.6, 0.6)], s=size,
               alpha=alpha, edgecolors='black', linewidths=0.4, depthshade=False)

def frame_axes(ax, radius, azim):
    ax.set_xlim(-radius, radius); ax.set_ylim(-radius, radius); ax.set_zlim(-radius, radius)
    ax.set_box_aspect((1, 1, 1), zoom=1.5)
    ax.view_init(elev=25, azim=azim)
    ax.set_axis_off()

# -----------------------------------------------------------------------------
# Static picture: the truth, then four generated samples

true_oriented = (true - true.mean(0)) @ orientation(true)  # lay the true structure out nicely
fig = plt.figure(figsize=(16, 3.6))
fig.suptitle(f"picofold.py\nAmino Acid Sequence: {seq_str}   (test window {idx})", fontsize=14, family='monospace')
radius = np.abs(true_oriented).max() + 1

ax = fig.add_subplot(1, 5, 1, projection='3d')
draw_chain(ax, true_oriented)
frame_axes(ax, radius, azim=-60)
ax.set_title("true structure", fontsize=11, family='monospace')

for k in range(4):
    ax = fig.add_subplot(1, 5, k + 2, projection='3d')
    draw_chain(ax, true_oriented, colored=False, lw=2, size=8, alpha=0.35)  # truth, faint gray
    draw_chain(ax, superpose(samples[k].cpu().numpy(), true_oriented))
    frame_axes(ax, radius, azim=-60)
    ax.set_title(f"generated sample {k + 1}\nlDDT {scores[k]:.2f}, dRMSD {errors[k]:.1f} A",
                 fontsize=11, family='monospace')

plt.tight_layout(rect=(0, 0, 1, 0.85))  # leave room for the two-line heading
plt.savefig('picofold_structure.png', dpi=110)
print(f"wrote picofold_structure.png (lDDT of the 4 samples: "
      f"{', '.join(f'{s:.2f}' for s in scores)})")

# -----------------------------------------------------------------------------
# Animation: sample 1 from noise to structure, then the truth fades in

trajectory = trajectories[0].cpu().numpy()                 # (steps+1, L, 3)
trajectory = trajectory - trajectory.mean(axis=1, keepdims=True)
trajectory = trajectory @ orientation(trajectory[-1])      # lay the final structure out nicely
steps = list(range(0, SAMPLE_STEPS + 1, 2))                # every 2nd step
HOLD = 30                                                  # extra frames at the end
FPS = 15
PAUSE = 2 * FPS                                            # then hold the last frame still for 2 s
LAST = len(steps) + HOLD - 1                               # index of the last moving frame
true_aligned = superpose(true_oriented, trajectory[-1])    # truth, in the sample's orientation

fig = plt.figure(figsize=(5.5, 5.5))
ax = fig.add_axes((0, 0, 1, 0.87), projection='3d')  # fill the frame; the strip on top is for the title

def draw_frame(f):
    f = min(f, LAST)                                       # during the pause, redraw the last frame
    ax.cla()
    step = steps[min(f, len(steps) - 1)]
    xyz = trajectory[step] - trajectory[step].mean(0)
    # Zoom out to fit early, noisy frames; settle on the final size
    r = max(radius, 1.05 * np.abs(xyz).max())
    if f >= len(steps):                                    # once folded, show the truth behind it
        draw_chain(ax, true_aligned - true_aligned.mean(0), colored=False,
                   lw=2, size=8, alpha=0.4)
    draw_chain(ax, xyz)
    frame_axes(ax, r, azim=-60 + 0.25 * f)                 # slowly turn the camera
    if f < len(steps):
        ax.set_title(f"picofold.py\nAmino Acid Sequence: {seq_str}\nt = {step / SAMPLE_STEPS:.2f}   (0 = noise, 1 = structure)",
                     family='monospace', fontsize=11)
    else:
        ax.set_title(f"picofold.py\nAmino Acid Sequence: {seq_str}\nt = 1.0. True structure in grey (lDDT {scores[0]:.2f})",
                     family='monospace', fontsize=11)

anim = FuncAnimation(fig, draw_frame, frames=LAST + 1 + PAUSE)
anim.save('picofold_folding.gif', writer=PillowWriter(fps=FPS))
print("wrote picofold_folding.gif")
